# deployment.yml
# kubectl apply -f deployment-be.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-be
  namespace: joseg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-be
  template:
    metadata:
      labels:
        app: backend-be
    spec:
      containers:
      - name: backend-be
        image: jose2506/backend:0.1                # Reemplaza con tu imagen Docker
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-credentials               # Nombre del Secret
              key: DATABASE_URL                        # Clave dentro del Secret
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: DATABASE_USERNAME
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: DATABASE_PASSWORD
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: API_KEY