# kubectl apply -f service-fe.yml
apiVersion: v1
kind: Service
metadata:
  name: frontend-fe
  namespace: joseg
spec:
  type: NodePort      #30000-32767  # Cambia a LoadBalancer si estás en un entorno de nube
  ports:
  - port: 30002       # Puerto que el Service expondrá
    targetPort: 4200  # Puerto en el contenedor donde tu aplicación escucha
    nodePort: 30002   # Puerto asignado en el nodo, opcional
  selector:
    app: frontend-fe  # Debe coincidir con las etiquetas del Deployment